# Generated by Django 4.2.2 on 2023-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, null=True)),
                ('faculty_id', models.CharField(max_length=100, null=True)),
                ('faculty_gender', models.CharField(max_length=100, null=True)),
                ('faculty_position', models.CharField(max_length=100, null=True)),
                ('faculty_code', models.CharField(max_length=100, null=True)),
                ('faculty_email', models.EmailField(max_length=254, null=True)),
                ('faculty_aadhar', models.CharField(max_length=100, null=True)),
                ('faculty_phone', models.CharField(max_length=250, null=True)),
                ('faculty_address', models.CharField(max_length=250, null=True)),
                ('faculty_dept', models.CharField(max_length=100, null=True)),
                ('faculty_year_join', models.DateField(null=True)),
                ('faculty_password', models.CharField(max_length=400, null=True)),
                ('faculty_status', models.CharField(max_length=100, null=True)),
                ('faculty_dob', models.DateField(null=True)),
                ('faculty_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'faculty_info_table',
            },
        ),
    ]
