# Generated by Django 4.2.2 on 2023-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=50, null=True)),
                ('receiver_id', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('message_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'message_table',
            },
        ),
    ]
