# Generated by Django 4.2.2 on 2023-06-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0002_message_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_head', models.CharField(max_length=50, null=True)),
                ('announcement_content', models.CharField(max_length=550, null=True)),
                ('announcement_id', models.CharField(max_length=50, null=True)),
                ('announcement_for', models.CharField(max_length=50, null=True)),
                ('announcement_link', models.CharField(max_length=250, null=True)),
                ('announcement_dpt', models.CharField(max_length=50, null=True)),
                ('announcement_date', models.DateTimeField(null=True)),
                ('announcement_S1', models.CharField(max_length=50, null=True)),
                ('announcement_S2', models.CharField(max_length=50, null=True)),
                ('announcement_S3', models.CharField(max_length=50, null=True)),
                ('announcement_S4', models.CharField(max_length=50, null=True)),
                ('announcement_S5', models.CharField(max_length=50, null=True)),
                ('announcement_S6', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'ann_info_table',
            },
        ),
    ]
