# Generated by Django 4.2.2 on 2023-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0003_announcement_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement_model',
            old_name='announcement_for',
            new_name='announcement_faculty',
        ),
        migrations.AddField(
            model_name='announcement_model',
            name='announcement_student',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
